DROP TABLE CLIENTES;
CREATE TABLE CLIENTES(
id NUMBER(10,0),
documento NUMBER(10,0),
nombre VARCHAR2(20),
edad NUMBER(2,0),
direccion VARCHAR2(20),
vinculo VARCHAR2(20) CHECK(vinculo IN('Estudiante', 'Profesor', 'Profesor_Invitado', 'Padre_De_Estudiante', 'Empleado', 'Egresado', 'Invitado_A_Evento'))
);

ALTER TABLE CLIENTES
MODIFY documento NUMBER(10,0) NOT NULL; 

ALTER TABLE CLIENTES
MODIFY nombre VARCHAR2(20) NOT NULL; 


ALTER TABLE CLIENTES
MODIFY edad NUMBER(10,0) NOT NULL; 


ALTER TABLE CLIENTES
MODIFY vinculo NOT NULL; 

ALTER TABLE CLIENTES
MODIFY id PRIMARY KEY; 
