CREATE TABLE HABITACIONES(
id NUMBER(20,0),
capacidad NUMBER(20,0),
compartido CHAR(1) CHECK(compartido IN('Y','N'))
);

ALTER TABLE HABITACIONES 
ADD categoría VARCHAR2(10);

ALTER TABLE HABITACIONES 
ADD CONSTRAINT CATENUM1 CHECK(categoría IN('ESTANDAR', 'SEMISUITE', 'SUITE'));

ALTER TABLE HABITACIONES 
ADD PRIMARY KEY (id);

ALTER TABLE HABITACIONES 
MODIFY compartido NOT NULL
MODIFY capacidad NOT NULL
MODIFY categoría NOT NULL;

