CREATE TABLE ESPACIOSYSERVICIOS(
idServicio NUMBER(20,0),
idEspacio NUMBER(20,0)
);
ALTER TABLE ESPACIOSYSERVICIOS
ADD CONSTRAINT FK_SERVICIO
FOREIGN KEY(idServicio) REFERENCES SERVICIOS(id);

ALTER TABLE ESPACIOSYSERVICIOS
ADD CONSTRAINT FK_ESPACIO
FOREIGN KEY(idEspacio) REFERENCES ESPACIOS(id);