CREATE TABLE RESERVASYESPACIOS(
idReserva NUMBER(20,0),
idEspacio NUMBER(20,0)
);
ALTER TABLE RESERVASYESPACIOS
ADD CONSTRAINT FK_RESERVA
FOREIGN KEY(idReserva) REFERENCES RESERVAS(id);

ALTER TABLE RESERVASYESPACIOS
ADD CONSTRAINT FK_ESPACIO
FOREIGN KEY(idEspacio) REFERENCES ESPACIOS(id);